# Generated by Django 4.2.23 on 2025-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='State',
            new_name='Country',
        ),
        migrations.AddField(
            model_name='customer',
            name='Province',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
